<a href="https://colab.research.google.com/github/aztcc/minerodedatos77/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introducción

La minería de datos (o Data Mining) es el proceso técnico de explorar y analizar grandes volúmenes de datos para descubrir patrones, tendencias o reglas que no son evidentes a simple vista.

Este concepto puede ser confundido con la Big Data, pero la diferencia es que Big Data es el proceso de almacenar y manejar volumenes masivos de información, mientras que la mineria de datos es la herramienta que analiza estos datos para obtener la información que se busca.

###Conceptos

####Mineria de datos

La minería de datos (o Data Mining) es el proceso técnico de explorar y analizar grandes volúmenes de datos para descubrir patrones, tendencias o reglas que no son evidentes a simple vista.

####Ciencia de datos

La Ciencia de Datos es un campo multidisciplinario que usa métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e ideas valiosas de grandes volúmenes de datos (Big Data), combinando estadística, matemáticas, informática e inteligencia artificial, con el fin de entender fenómenos, predecir tendencias y apoyar la toma de decisiones informadas en diversas áreas, desde negocios hasta ciencia.

#####iPython Magic commands

In [1]:
# Sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

85 µs ± 37.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [2]:
# El comando %%timeit sirve para evaluar el desempeño
# a traves de multiples lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

91.4 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#####iPython and shell commands

In [3]:
!ls

sample_data


In [4]:
!pwd

/content


In [7]:
!echo "Printing from the shell"

Printing from the shell


In [8]:
contents = !ls

In [10]:
directory = !pwd

In [11]:
print(directory)

['/content']


In [12]:
type(directory)

IPython.utils.text.SList

In [9]:
print(contents)

['sample_data']


In [13]:
message = "hello from Python"

In [14]:
!echo {message}

hello from Python


In [23]:
%cd /content/sample_data/

/content/sample_data


In [24]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [25]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


#####Understanding data types in Python

In [26]:
import numpy as np

In [27]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [28]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [29]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [30]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [31]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

####Help and Documentation in IPython

In [ ]:
# La funcion help nos muestra la ayuda
help(len)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando el caracter ?
len?

In [ ]:
# Definicion de una lista y su comando de ayuda
 L = [1, 2, 3]
 L.insert?

In [ ]:
# Otra dorma de obtener ayuda de la funcion
help(L.insert)

Help on built-in function insert:

insert(index, object, /) method of builtins.list instance
    Insert object before index.



In [ ]:
L.insert(0,-1)

In [ ]:
# Definicion de una funcion
def square(a):
  """Regresa el cuadrado de a."""
  return a ** 2

In [ ]:
help(square)

Help on function square in module __main__:

square(a)
    Regresa el cuadrado de a.



In [ ]:
square??

##Segundo Parcial

##Tercer Parcial