<a href="https://colab.research.google.com/github/aztcc/minerodedatos77/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

##Primer Parcial

###Introducción

La minería de datos (o Data Mining) es el proceso técnico de explorar y analizar grandes volúmenes de datos para descubrir patrones, tendencias o reglas que no son evidentes a simple vista.

Este concepto puede ser confundido con la Big Data, pero la diferencia es que Big Data es el proceso de almacenar y manejar volumenes masivos de información, mientras que la mineria de datos es la herramienta que analiza estos datos para obtener la información que se busca.

###Conceptos

####Mineria de datos

La minería de datos (o Data Mining) es el proceso técnico de explorar y analizar grandes volúmenes de datos para descubrir patrones, tendencias o reglas que no son evidentes a simple vista.

####Ciencia de datos

La Ciencia de Datos es un campo multidisciplinario que usa métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e ideas valiosas de grandes volúmenes de datos (Big Data), combinando estadística, matemáticas, informática e inteligencia artificial, con el fin de entender fenómenos, predecir tendencias y apoyar la toma de decisiones informadas en diversas áreas, desde negocios hasta ciencia.

#####iPython Magic commands

In [3]:
# Sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

75.7 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
# El comando %%timeit sirve para evaluar el desempeño
# a traves de multiples lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

76.6 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#####iPython and shell commands

In [5]:
!ls

sample_data


In [6]:
!pwd

/content


In [7]:
!echo "Printing from the shell"

Printing from the shell


In [8]:
contents = !ls

In [9]:
directory = !pwd

In [10]:
print(directory)

['/content']


In [11]:
type(directory)

IPython.utils.text.SList

In [12]:
print(contents)

['sample_data']


In [13]:
message = "hello from Python"

In [14]:
!echo {message}

hello from Python


In [15]:
%cd /content/sample_data/

/content/sample_data


In [16]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [17]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


#####Understanding data types in Python

In [18]:
import numpy as np

In [19]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [20]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [21]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [22]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [23]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

####Help and Documentation in IPython

In [24]:
# La funcion help nos muestra la ayuda
help(len)


Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [25]:
# Otra forma de obtener ayuda es utilizando el caracter ?
len?

In [32]:
# Definicion de una lista y su comando de ayuda
L = [1, 2, 3]
L.insert?

In [33]:
# Otra dorma de obtener ayuda de la funcion
help(L.insert)

Help on built-in function insert:

insert(index, object, /) method of builtins.list instance
    Insert object before index.



In [34]:
L.insert(0,-1)

In [35]:
# Definicion de una funcion
def square(a):
  """Regresa el cuadrado de a."""
  return a ** 2

In [36]:
help(square)

Help on function square in module __main__:

square(a)
    Regresa el cuadrado de a.



In [37]:
square??

####Creating Arrays from Scratch

In [38]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [41]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.random.random((3, 3))

array([[0.47366715, 0.24158089, 0.35464147],
       [0.83321519, 0.04120319, 0.6424395 ],
       [0.28724548, 0.07363768, 0.16101125]])

In [45]:
np.random.normal(21, 1, (3, 5))

array([[19.46455465, 20.08695049, 21.75097052, 21.48416463, 19.60948701],
       [19.05876544, 21.80346457, 21.49561539, 19.48978424, 19.14445767],
       [21.19164348, 20.52191536, 23.49530914, 22.25866704, 23.67050148]])

####The Basics of NumPy Arrays

In [46]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [47]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [48]:
print("dtype:", x3.dtype)

dtype: int64


In [49]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


####Array Indexing: Accessing Single Elements

In [50]:
x1

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[0]

np.int64(5)

In [54]:
x1[4]

np.int64(7)

In [55]:
x1[-1]

np.int64(9)

In [56]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[0, 0]

np.int64(3)

In [58]:
x2[2, -1]

np.int64(7)

####Promedio (average) y promedio ponderado

In [59]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

####Correlacion

In [60]:
corr = np.corrcoef([1,2,3], [1,5,7])

##Segundo Parcial

##Tercer Parcial